FROM ubuntu

RUN apt-get clean && apt-get -y update --fix-missing
RUN apt-get -y install --fix-missing
#RUN apt-get -y install --fix-missing cmake make git perl-modules-5.34 build-essential libssl-dev mysql-client zlib1g-dev libmysqlclient-dev libboost-all-dev
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata git sudo build-essential autoconf libtool libssl-dev zlib1g-dev librdkafka-dev pkg-config cmake gcc git g++ mysql-client libmysqlclient-dev libboost-all-dev libssl-dev && apt-get clean
WORKDIR /root
RUN git clone https://github.com/tdv/redis-cpp.git 
RUN cd redis-cpp && mkdir build && cd build && cmake .. && make && sudo make install && cd .. && cd .. 
RUN git clone -b poco-1.11.7-release https://github.com/pocoproject/poco.git
RUN cd poco && mkdir cmake-build && cd cmake-build && cmake .. && make && make install && cd .. && cd ..
RUN git clone https://github.com/edenhill/librdkafka.git 
RUN cd librdkafka && ./configure && make && sudo make install && cd ..
RUN git clone https://github.com/mfontanini/cppkafka 
RUN cd cppkafka && mkdir build && cd build && cmake .. && make && sudo make install && cd .. && cd .. 



